/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a list of books
         * @description Retrieves a list of books; paginated, sorted and filtered by attributes.
         */
        get: operations["getBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a book
         * @description Retrieves a specific book by id, use "random" to get a random book.
         */
        get: operations["getBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a list of chapters of a given book
         * @description Retrieves a list of chapters of a given book; paginated, sorted and filtered by attributes.
         */
        get: operations["getChapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{book_id}/chapters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a chapter of a given book
         * @description Retrieves a specific chapter of a given book by id, use "random" to get a random chapter.
         */
        get: operations["getChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a list of characters
         * @description Retrieves a list of characters; paginated, sorted and filtered by attributes.
         */
        get: operations["getCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a character
         * @description Retrieves a specific character by id, use "random" to get a random character.
         */
        get: operations["getCharacter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a list of movies
         * @description Retrieves a list of movies; paginated, sorted and filtered by attributes.
         */
        get: operations["getMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/movies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a movie
         * @description Retrieves a specific movie by id, use "random" to get a random movie.
         */
        get: operations["getMovie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/potions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a list of potions
         * @description Retrieves a list of potions; paginated, sorted and filtered by attributes.
         */
        get: operations["getPotions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/potions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a potion
         * @description Retrieves a specific potion by id, use "random" to get a random potion.
         */
        get: operations["getPotion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a list of spells
         * @description Retrieves a list of spells; paginated, sorted and filtered by attributes.
         */
        get: operations["getSpells"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spells/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a spell
         * @description Retrieves a specific spell by id, use "random" to get a random spell.
         */
        get: operations["getSpell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Meta information about the response.
         * @example {
         *       "copyright": "Copyright © Potter DB 2023",
         *       "generated_at": "2023-10-14T21:53:54+02:00"
         *     }
         */
        meta: {
            copyright?: string;
            /** Format: date_time */
            generated_at?: string;
        };
        pagination_links: {
            /** @description The current page of data. */
            self: string | null;
            /** @description The current page of data. */
            current?: string | null;
            /** @description The first page of data. */
            first?: string | null;
            /** @description The prev page of data. */
            prev?: string | null;
            /** @description The next page of data. */
            next?: string | null;
            /** @description The last page of data. */
            last?: string | null;
        };
        /**
         * @example {
         *       "errors": [
         *         {
         *           "title": "Not found",
         *           "status": "404"
         *         }
         *       ]
         *     }
         */
        not_found: {
            errors?: {
                /** @enum {string} */
                status?: "404";
                /** @example Not found */
                title?: string;
            }[];
        };
        success_without_data: {
            meta?: components["schemas"]["meta"];
            links?: components["schemas"]["pagination_links"];
        };
        /**
         * Format: uuid
         * @example c1637a49-3cc8-4285-93a1-28e6579f1f20
         */
        uuid_path: string;
        /** @example harry-potter-and-the-philosopher-s-stone */
        slug_path: string;
        /**
         * @example [
         *       {
         *         "id": "c1637a49-3cc8-4285-93a1-28e6579f1f20",
         *         "type": "chapter"
         *       }
         *     ]
         */
        to_many_chapters_relationship: components["schemas"]["to_one_chapter_relationship"][];
        to_one_chapter_relationship: {
            /** @description The unique identifier of the chapter. */
            id: string;
            /** @enum {string} */
            type: "chapter";
        };
        to_one_book_relationship: {
            /** @description The unique identifier of the book. */
            id: string;
            /** @enum {string} */
            type: "book";
        };
        /** @description Representation of a book. */
        book: {
            /**
             * @description The unique identifier of the book. Must be a valid UUID v4.
             * @example c1637a49-3cc8-4285-93a1-28e6579f1f20
             */
            id: string;
            /** @enum {string} */
            type: "book";
            attributes: {
                /** @example harry-potter-and-the-philosopher-s-stone */
                slug: string;
                /** @example Harry Potter and the Philosopher's Stone */
                title: string;
                summary?: string | null;
                author?: string | null;
                /** Format: date */
                release_date?: string | null;
                dedication?: string | null;
                pages?: number | null;
                order?: number | null;
                /** Format: uri */
                cover?: string | null;
                /** Format: uri */
                wiki?: string | null;
            };
            relationships?: {
                chapters?: {
                    data?: components["schemas"]["to_many_chapters_relationship"];
                };
            };
            links?: {
                /** @example /v1/books/c1637a49-3cc8-4285-93a1-28e6579f1f20 */
                self?: string;
            };
        };
        /** @description Representation of a chapter. */
        chapter: {
            /**
             * @description The unique identifier of the chapter. Must be a valid UUID v4.
             * @example c1637a49-3cc8-4285-93a1-28e6579f1f20
             */
            id: string;
            /** @enum {string} */
            type: "chapter";
            attributes: {
                /**
                 * Format: slug
                 * @example the-boy-who-lived
                 */
                slug: string;
                /** @example The Boy Who Lived */
                title: string;
                summary?: string | null;
                order?: number | null;
            };
            relationships?: {
                book?: {
                    data?: components["schemas"]["to_one_book_relationship"];
                };
            };
            links?: {
                /** @example /v1/books/7f8d9b7c-5a7c-4f7c-9d5a-1d8e6f7a8b9d/chapters/c1637a49-3cc8-4285-93a1-28e6579f1f20 */
                self?: string;
            };
        };
        /** @description Representation of a character. */
        character: {
            /**
             * @description The unique identifier of the character. Must be a valid UUID v4.
             * @example c1637a49-3cc8-4285-93a1-28e6579f1f20
             */
            id: string;
            /** @enum {string} */
            type: "character";
            attributes: {
                /** @example harry-potter */
                slug: string;
                /** @example Harry James Potter */
                name: string;
                born?: string | null;
                died?: string | null;
                gender?: string | null;
                species?: string | null;
                height?: string | null;
                weight?: string | null;
                hair_color?: string | null;
                eye_color?: string | null;
                skin_color?: string | null;
                blood_status?: string | null;
                marital_status?: string | null;
                nationality?: string | null;
                animagus?: string | null;
                boggart?: string | null;
                house?: string | null;
                patronus?: string | null;
                alias_names?: string[];
                family_members?: string[];
                jobs?: string[];
                romances?: string[];
                titles?: string[];
                wands?: string[];
                /** Format: uri */
                image?: string | null;
                /** Format: uri */
                wiki?: string | null;
            };
            links?: {
                /** @example /v1/characters/c1637a49-3cc8-4285-93a1-28e6579f1f20 */
                self?: string;
            };
        };
        /** @description Representation of a movie. */
        movie: {
            /**
             * @description The unique identifier of the movie. Must be a valid UUID v4.
             * @example c1637a49-3cc8-4285-93a1-28e6579f1f20
             */
            id: string;
            /** @enum {string} */
            type: "movie";
            attributes: {
                /** @example harry-potter-and-the-philosopher-s-stone */
                slug: string;
                /** @example Harry Potter and the Philosopher's Stone */
                title: string;
                summary?: string | null;
                director?: string[];
                screenwriters?: string[];
                producers?: string[];
                cinematographers?: string[];
                editors?: string[];
                distributors?: string[];
                music_composers?: string[];
                release_date?: string | null;
                running_time?: string | null;
                budget?: string | null;
                box_office?: string | null;
                rating?: string | null;
                order?: number | null;
                /** Format: uri */
                trailer?: string | null;
                /** Format: uri */
                image?: string | null;
                /** Format: uri */
                wiki?: string | null;
            };
            links?: {
                /** @example /v1/movies/c1637a49-3cc8-4285-93a1-28e6579f1f20 */
                self?: string;
            };
        };
        /** @description Representation of a potion. */
        potion: {
            /**
             * @description The unique identifier of the potion. Must be a valid UUID v4.
             * @example c1637a49-3cc8-4285-93a1-28e6579f1f20
             */
            id: string;
            /** @enum {string} */
            type: "potion";
            attributes: {
                /** @example ageing-potion */
                slug: string;
                /** @example Ageing Potion */
                name: string;
                effect?: string | null;
                side_effects?: string | null;
                characteristics?: string | null;
                time?: string | null;
                difficulty?: string | null;
                ingredients?: string | null;
                inventors?: string | null;
                manufacturers?: string | null;
                /** Format: uri */
                image?: string | null;
                /** Format: uri */
                wiki?: string | null;
            };
            links?: {
                /** @example /v1/potions/c1637a49-3cc8-4285-93a1-28e6579f1f20 */
                self?: string;
            };
        };
        /** @description Representation of a spells. */
        spell: {
            /**
             * @description The unique identifier of the spells. Must be a valid UUID v4 or slug.
             * @example c1637a49-3cc8-4285-93a1-28e6579f1f20
             */
            id: string;
            /** @enum {string} */
            type: "spell";
            attributes: {
                /** @example age-line */
                slug: string;
                /** @example Age Line */
                name: string;
                incantation?: string | null;
                category?: string | null;
                effect?: string | null;
                light?: string | null;
                hand?: string | null;
                creator?: string | null;
                /** Format: uri */
                image?: string | null;
                /** Format: uri */
                wiki?: string | null;
            };
            links?: {
                /** @example /v1/spells/c1637a49-3cc8-4285-93a1-28e6579f1f20 */
                self?: string;
            };
        };
    };
    responses: never;
    parameters: {
        /** @description The number of returned results per page (between 1 and 100). */
        page_size: number;
        /** @description The page number of the returned results. */
        page_number: number;
        /** @description Sort books by the given field. If prefixed with "-" sort is descending. */
        sort_books: ("author" | "-author" | "dedication" | "-dedication" | "pages" | "-pages" | "release_date" | "-release_date" | "summary" | "-summary" | "title" | "-title")[];
        /**
         * @description Filter books by the given field. Use ransack matchers to filter. \
         *      See [Ransack Search Matchers] \
         *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
         *      Example: `{ "filter[title_cont]": "Azkaban" }`
         */
        filter_books_by: Record<string, never> | null;
        /** @description Sort books by the given field. If prefixed with "-" sort is descending. */
        sort_chapters: ("order" | "-order" | "summary" | "-summary" | "title" | "-title")[];
        /**
         * @description Filter chapters by the given field. Use ransack matchers to filter. \
         *      See [Ransack Search Matchers] \
         *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
         *      Example: `{ "filter[title_cont]": "Glass" }`
         */
        filter_chapters_by: Record<string, never> | null;
        /** @description Sort characters by the given field. If prefixed with "-" sort is descending. */
        sort_characters: ("alias_names" | "-alias_names" | "animagus" | "-animagus" | "blood_status" | "-blood_status" | "boggart" | "-boggart" | "born" | "-born" | "died" | "-died" | "eye_color" | "-eye_color" | "family_members" | "-family_members" | "gender" | "-gender" | "hair_color" | "-hair_color" | "height" | "-height" | "house" | "-house" | "jobs" | "-jobs" | "marital_status" | "-marital_status" | "name" | "-name" | "nationality" | "-nationality" | "patronus" | "-patronus" | "romances" | "-romances" | "skin_color" | "-skin_color" | "species" | "-species" | "titles" | "-titles" | "wands" | "-wands" | "weight" | "-weight")[];
        /**
         * @description Filter characters by the given field. Use ransack matchers to filter. \
         *      See [Ransack Search Matchers] \
         *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
         *      Example: `{ "filter[name_cont]": "Weasley" }`
         */
        filter_characters_by: Record<string, never> | null;
        /** @description Sort movies by the given field. If prefixed with "-" sort is descending. */
        sort_movies: ("box_office" | "-box_office" | "budget" | "-budget" | "cinematographers" | "-cinematographers" | "directors" | "-directors" | "distributors" | "-distributors" | "editors" | "-editors" | "music_composers" | "-music_composers" | "producers" | "-producers" | "rating" | "-rating" | "release_date" | "-release_date" | "running_time" | "-running_time" | "screenwriters" | "-screenwriters" | "summary" | "-summary" | "title" | "-title")[];
        /**
         * @description Filter movies by the given field. Use ransack matchers to filter. \
         *      See [Ransack Search Matchers] \
         *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
         *      Example: `{ "filter[title_cont]": "Fantastic" }`
         */
        filter_movies_by: Record<string, never> | null;
        /** @description Sort potions by the given field. If prefixed with "-" sort is descending. */
        sort_potions: ("characteristics" | "-characteristics" | "difficulty" | "-difficulty" | "effect" | "-effect" | "ingredients" | "-ingredients" | "inventors" | "-inventors" | "manufacturers" | "-manufacturers" | "name" | "-name" | "side_effects" | "-side_effects" | "time" | "-time")[];
        /**
         * @description Filter potions by the given field. Use ransack matchers to filter. \
         *      See [Ransack Search Matchers] \
         *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
         *      Example: `{ "filter[name_cont]": "Age" }`
         */
        filter_potions_by: Record<string, never> | null;
        /** @description Sort spells by the given field. If prefixed with "-" sort is descending. */
        sort_spells: ("category" | "-category" | "creator" | "-creator" | "effect" | "-effect" | "hand" | "-hand" | "incantation" | "-incantation" | "light" | "-light" | "name" | "-name")[];
        /**
         * @description Filter spells by the given field. Use ransack matchers to filter. \
         *      See [Ransack Search Matchers] \
         *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
         *      Example: `{ "filter[name_cont]": "Age" }`
         */
        filter_spells_by: Record<string, never> | null;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBooks: {
        parameters: {
            query?: {
                /** @description The number of returned results per page (between 1 and 100). */
                "page[size]"?: components["parameters"]["page_size"];
                /** @description The page number of the returned results. */
                "page[number]"?: components["parameters"]["page_number"];
                /** @description Sort books by the given field. If prefixed with "-" sort is descending. */
                sort?: components["parameters"]["sort_books"];
                /**
                 * @description Filter books by the given field. Use ransack matchers to filter. \
                 *      See [Ransack Search Matchers] \
                 *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
                 *      Example: `{ "filter[title_cont]": "Azkaban" }`
                 */
                filter?: components["parameters"]["filter_books_by"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of books */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["book"][];
                    } & components["schemas"]["success_without_data"];
                };
            };
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier of the book. Must be a valid UUID v4 or slug. */
                id: components["schemas"]["uuid_path"] | components["schemas"]["slug_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A single book */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["book"];
                    } & components["schemas"]["success_without_data"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["not_found"];
                };
            };
        };
    };
    getChapters: {
        parameters: {
            query?: {
                /** @description The number of returned results per page (between 1 and 100). */
                "page[size]"?: components["parameters"]["page_size"];
                /** @description The page number of the returned results. */
                "page[number]"?: components["parameters"]["page_number"];
                /** @description Sort books by the given field. If prefixed with "-" sort is descending. */
                sort?: components["parameters"]["sort_chapters"];
                /**
                 * @description Filter chapters by the given field. Use ransack matchers to filter. \
                 *      See [Ransack Search Matchers] \
                 *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
                 *      Example: `{ "filter[title_cont]": "Glass" }`
                 */
                filter?: components["parameters"]["filter_chapters_by"];
            };
            header?: never;
            path: {
                /** @description The identifier of the book. Must be a valid UUID v4 or slug. */
                id: components["schemas"]["uuid_path"] | components["schemas"]["slug_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of chapters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["chapter"][];
                    } & components["schemas"]["success_without_data"];
                };
            };
            /** @description Chapter not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["not_found"];
                };
            };
        };
    };
    getChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier of the book. Must be a valid UUID v4 or slug. */
                book_id: components["schemas"]["uuid_path"] | components["schemas"]["slug_path"];
                /** @description The identifier of the book's chapter. Must be a valid UUID v4 or slug. */
                id: components["schemas"]["uuid_path"] | components["schemas"]["slug_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A single chapter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["chapter"];
                    } & components["schemas"]["success_without_data"];
                };
            };
            /** @description Book or Chapter not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["not_found"];
                };
            };
        };
    };
    getCharacters: {
        parameters: {
            query?: {
                /** @description The number of returned results per page (between 1 and 100). */
                "page[size]"?: components["parameters"]["page_size"];
                /** @description The page number of the returned results. */
                "page[number]"?: components["parameters"]["page_number"];
                /** @description Sort characters by the given field. If prefixed with "-" sort is descending. */
                sort?: components["parameters"]["sort_characters"];
                /**
                 * @description Filter characters by the given field. Use ransack matchers to filter. \
                 *      See [Ransack Search Matchers] \
                 *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
                 *      Example: `{ "filter[name_cont]": "Weasley" }`
                 */
                filter?: components["parameters"]["filter_characters_by"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of characters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["character"][];
                    } & components["schemas"]["success_without_data"];
                };
            };
        };
    };
    getCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier of the character. Must be a valid UUID v4 or slug. */
                id: components["schemas"]["uuid_path"] | components["schemas"]["slug_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A single character */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["character"];
                    } & components["schemas"]["success_without_data"];
                };
            };
            /** @description Character not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["not_found"];
                };
            };
        };
    };
    getMovies: {
        parameters: {
            query?: {
                /** @description The number of returned results per page (between 1 and 100). */
                "page[size]"?: components["parameters"]["page_size"];
                /** @description The page number of the returned results. */
                "page[number]"?: components["parameters"]["page_number"];
                /** @description Sort movies by the given field. If prefixed with "-" sort is descending. */
                sort?: components["parameters"]["sort_movies"];
                /**
                 * @description Filter movies by the given field. Use ransack matchers to filter. \
                 *      See [Ransack Search Matchers] \
                 *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
                 *      Example: `{ "filter[title_cont]": "Fantastic" }`
                 */
                filter?: components["parameters"]["filter_movies_by"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of movies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["movie"][];
                    } & components["schemas"]["success_without_data"];
                };
            };
        };
    };
    getMovie: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier of the movie. Must be a valid UUID v4 or slug. */
                id: components["schemas"]["uuid_path"] | components["schemas"]["slug_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A single movie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["movie"];
                    } & components["schemas"]["success_without_data"];
                };
            };
            /** @description Movie not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["not_found"];
                };
            };
        };
    };
    getPotions: {
        parameters: {
            query?: {
                /** @description The number of returned results per page (between 1 and 100). */
                "page[size]"?: components["parameters"]["page_size"];
                /** @description The page number of the returned results. */
                "page[number]"?: components["parameters"]["page_number"];
                /** @description Sort potions by the given field. If prefixed with "-" sort is descending. */
                sort?: components["parameters"]["sort_potions"];
                /**
                 * @description Filter potions by the given field. Use ransack matchers to filter. \
                 *      See [Ransack Search Matchers] \
                 *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
                 *      Example: `{ "filter[name_cont]": "Age" }`
                 */
                filter?: components["parameters"]["filter_potions_by"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of potions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["potion"][];
                    } & components["schemas"]["success_without_data"];
                };
            };
        };
    };
    getPotion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier of the potion. Must be a valid UUID v4 or slug. */
                id: components["schemas"]["uuid_path"] | components["schemas"]["slug_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A single potion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["potion"];
                    } & components["schemas"]["success_without_data"];
                };
            };
            /** @description Potion not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["not_found"];
                };
            };
        };
    };
    getSpells: {
        parameters: {
            query?: {
                /** @description The number of returned results per page (between 1 and 100). */
                "page[size]"?: components["parameters"]["page_size"];
                /** @description The page number of the returned results. */
                "page[number]"?: components["parameters"]["page_number"];
                /** @description Sort spells by the given field. If prefixed with "-" sort is descending. */
                sort?: components["parameters"]["sort_spells"];
                /**
                 * @description Filter spells by the given field. Use ransack matchers to filter. \
                 *      See [Ransack Search Matchers] \
                 *      (https://activerecord-hackery.github.io/ransack/getting-started/search-matches/). \
                 *      Example: `{ "filter[name_cont]": "Age" }`
                 */
                filter?: components["parameters"]["filter_spells_by"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of spells */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["spell"][];
                    } & components["schemas"]["success_without_data"];
                };
            };
        };
    };
    getSpell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier of the spell. Must be a valid UUID v4 or slug. */
                id: components["schemas"]["uuid_path"] | components["schemas"]["slug_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A single spell */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": {
                        data: components["schemas"]["spell"];
                    } & components["schemas"]["success_without_data"];
                };
            };
            /** @description Spell not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["not_found"];
                };
            };
        };
    };
}
